config/routes.rb
Beacon::Application.routes.draw do
 

	match 'ibeacon/:id', to: 'ibeacons#show'

 	get "users/new"

	root to: 'static_pages#home'
	
	match '/signup', to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete	
	
	match '/addbeacon', to: 'ibeacons#new'
	
	
	match '/help', to: 'static_pages#help'
	match '/about', to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'
	
	
  	resources :microposts

  	resources :users
	resources :sessions, only: [:new, :create, :destroy]
	resources :ibeacons, only: [:create, :edit, :destroy, :update]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
	attr_accessible :email, :name, :password, :password_confirmation
	has_secure_password
	
	before_save { |user| user.email = email.downcase }
	before_save :create_remember_token
	
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
		
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	
	has_many :microposts, dependent: :destroy
	has_many :ibeacons, dependent: :destroy
	
	private
	def create_remember_token
		self.remember_token = SecureRandom.urlsafe_base64
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: :destroy
	
	respond_to :html, :json
	
	def edit
	end
		
	def destroy
	    User.find(params[:id]).destroy	
		flash[:success] = "User destroyed."
		redirect_to users_path
	end	

	def index
		@users = User.paginate(page: params[:page])
	end
	
	def show
		@user = User.find(params[:id])
		@ibeacons = @user.ibeacons.paginate(page: params[:page]) 

		
		
		#format.json { render json: @user, :except=>  [:password, :password_confirm] }
		#format.json { render json: @user }
		respond_with @user       # added to respond with json
	end
	
	def new
		@user = User.new		
	end
	
	def create
		@user = User.new(params[:user]) 
		if @user.save
			sign_in @user
			flash[:success] = "Welcome to the iBeacon App - Bionex!"
	    	redirect_to @user
		else
			render 'new' 
		end
	end
	
#	def edit
#		@user = User.find(params[:id])
#	end	
	

	def update
		if @user.update_attributes(params[:user])
			flash[:success] = "Profile updated"
			sign_in @user
			redirect_to @user
		else
			render 'edit'
		end
	end
	
	
private

	def signed_in_user
		unless signed_in?
		store_location
		redirect_to signin_path, notice: "Please sign in."
		end
	end
	
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end	
	
	
	
	
	def admin_user
		redirect_to(root_path) unless current_user.admin?
	end	
	
end

app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user,size )
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png" 
		
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end 
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
	| <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
	<% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		
		<%= f.label :name %>
		<%= f.text_field :name %>
		
		<%= f.label :email %>
		<%= f.text_field :email %>
		
		<%= f.label :password %>
		<%= f.password_field :password %>
		
		<%= f.label :password_confirmation, "Confirm Password" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
	<% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %> 
<h1>Sign up</h1>

	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@user) do |f| %>
			
				<%= render 'shared/error_messages', object: f.object %>
		
				<%= f.label :name %>
				<%= f.text_field :name %>
				
				<%= f.label :email %>
				<%= f.text_field :email %>
				
				<%= f.label :password %>
				<%= f.password_field :password %>
				
				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>
				
				<%= f.submit "Create my account", class: "btn btn-large btn-primary" %> 
			<% end %>
		</div>
	</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4"> 
		<section>
			<h1>
				<%= @user.name %>
			</h1>
    	</section>
  	</aside>
	<div class="span8">
		<% if @user.ibeacons.any? %>
			<h3>iBeacons (<%= @user.ibeacons.count %>)</h3>
			<ol class="ibeacons">
				<%= render @ibeacons %>
			</ol>
			<%= will_paginate @ibeacons %>
		<% end %>
	</div>
</div>


<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Add New iBeacon', addbeacon_path(@ibeacon) %> |
<%= link_to 'Back', users_path %>

app/views/users/show.json.erb
{
    "name": "<%= @user.name.to_json %>",
    "admin": "<%= @user.admin.to_json %>"
}